"""Autoresearch adapter — deep-dives into docs, issues, and papers.

Live mode uses the claude CLI to perform structured research on the
focus areas provided during the interview.
"""

from __future__ import annotations

from textwrap import dedent

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_REPORT = """\
# Research Report

## Focus Areas
{focus}

## Findings
- **Libraries**: Analysis pending full autoresearch integration.
- **Edge Cases**: Identified areas requiring deeper investigation.
- **References**: Queued for academic paper search.

## Recommendations
1. Proceed with initial architecture while research continues.
2. Flag blocking unknowns for async resolution.

---
*Generated by FlowState (mock mode)*
"""

RESEARCH_SYSTEM_PROMPT = dedent("""\
    You are an expert technical researcher. Produce a concise Markdown research
    report. Keep it focused — no more than 500 lines. For each focus area:
    1. Search for current best practices and known issues.
    2. Compare top 2-3 approaches with pros/cons.
    3. Note critical edge cases.
    4. Give a concrete recommendation.
    Output ONLY the Markdown report, no preamble. Be direct and brief.
""").strip()


def _build_research_prompt(answers: InterviewAnswers) -> str:
    parts = [f"# Research Request\n\n## Focus\n{answers.research_focus}"]
    if answers.core_problem:
        parts.append(f"\n## Context\nCore problem: {answers.core_problem}")
    if answers.architecture_pattern:
        parts.append(f"\nArchitecture constraint: {answers.architecture_pattern}")
    parts.append(
        "\n\nProduce a structured Markdown research report covering the focus "
        "areas above. Include library comparisons, edge cases, and recommendations."
    )
    return "\n".join(parts)


class AutoresearchAdapter(ToolAdapter):
    name = "autoresearch"

    def execute(self, answers: InterviewAnswers) -> ToolResult:
        report_dir = self.root / "research"
        report_dir.mkdir(exist_ok=True)
        report_path = report_dir / "report.md"

        if self.dry_run:
            content = MOCK_REPORT.format(
                focus=answers.research_focus or "Not specified"
            )
            report_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Research report written to {report_path}",
                artifacts=[str(report_path)],
            )

        prompt = _build_research_prompt(answers)
        br = self.bridge.run(
            prompt,
            system_prompt=RESEARCH_SYSTEM_PROMPT,
            allowed_tools=["WebSearch", "WebFetch", "Read"],
            max_turns=8,
        )

        if br.success and br.output.strip():
            report_path.write_text(br.output)
            return ToolResult(
                success=True,
                output=f"Research report written to {report_path}",
                artifacts=[str(report_path)],
            )

        return self.bridge_to_result(br)
