"""Autoresearch adapter — deep-dives into docs, issues, and papers."""

from __future__ import annotations

from pathlib import Path

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_REPORT = """\
# Research Report

## Focus Areas
{focus}

## Findings
- **Libraries**: Analysis pending full autoresearch integration.
- **Edge Cases**: Identified areas requiring deeper investigation.
- **References**: Queued for academic paper search.

## Recommendations
1. Proceed with initial architecture while research continues.
2. Flag blocking unknowns for async resolution.

---
*Generated by FlowState (mock mode)*
"""


class AutoresearchAdapter(ToolAdapter):
    name = "autoresearch"

    def execute(self, answers: InterviewAnswers) -> ToolResult:
        report_dir = self.root / "research"
        report_dir.mkdir(exist_ok=True)
        report_path = report_dir / "report.md"

        if self.dry_run:
            content = MOCK_REPORT.format(focus=answers.research_focus or "Not specified")
            report_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Research report written to {report_path}",
                artifacts=[str(report_path)],
            )

        result = self.run_cmd(["autoresearch", "run", "--focus", answers.research_focus])
        if result.success and result.output:
            report_path.write_text(result.output)
            result.artifacts.append(str(report_path))
        return result
