"""GSD adapter — roadmap and state management."""

from __future__ import annotations

from pathlib import Path

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_ROADMAP = """\
# Roadmap

## Milestones
{milestones}

## Status
- Phase: Initialization
- State: Ready for planning

---
*Generated by FlowState (mock mode)*
"""


class GSDAdapter(ToolAdapter):
    name = "gsd"

    def new_project(self, answers: InterviewAnswers) -> ToolResult:
        if self.dry_run:
            roadmap_path = self.root / "ROADMAP.md"
            milestone_text = "\n".join(
                f"{i}. {m}" for i, m in enumerate(answers.milestones, 1)
            ) or "1. Define milestones"
            roadmap_path.write_text(MOCK_ROADMAP.format(milestones=milestone_text))
            return ToolResult(
                success=True,
                output=f"[dry-run] Roadmap written to {roadmap_path}",
                artifacts=[str(roadmap_path)],
            )

        return self.run_cmd(["gsd", "new-project"])
