"""GSD adapter — roadmap and state management.

Live mode invokes the real GSD skill system (`/gsd:new-project`) through
the claude CLI. GSD creates .planning/ with PROJECT.md, REQUIREMENTS.md,
ROADMAP.md, and STATE.md.
"""

from __future__ import annotations

from pathlib import Path

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_ROADMAP = """\
# Roadmap

## Milestones
{milestones}

## Status
- Phase: Initialization
- State: Ready for planning

---
*Generated by FlowState (mock mode)*
"""


class GSDAdapter(ToolAdapter):
    name = "gsd"

    def new_project(self, answers: InterviewAnswers) -> ToolResult:
        if self.dry_run:
            roadmap_path = self.root / "ROADMAP.md"
            milestone_text = "\n".join(
                f"{i}. {m}" for i, m in enumerate(answers.milestones, 1)
            ) or "1. Define milestones"
            roadmap_path.write_text(MOCK_ROADMAP.format(milestones=milestone_text))
            return ToolResult(
                success=True,
                output=f"[dry-run] Roadmap written to {roadmap_path}",
                artifacts=[str(roadmap_path)],
            )

        # Invoke the real GSD skill via claude CLI
        br = self.bridge.invoke_skill("gsd:new-project", "--auto")

        # Collect artifacts that GSD creates
        artifacts = []
        planning = self.root / ".planning"
        for name in ("PROJECT.md", "REQUIREMENTS.md", "ROADMAP.md", "STATE.md"):
            p = planning / name
            if p.exists():
                artifacts.append(str(p))

        return ToolResult(
            success=br.success,
            output=br.output[:500] if br.success else "",
            artifacts=artifacts,
            error=br.error,
        )

    def plan_phase(self, phase: int) -> ToolResult:
        """Plan a specific phase via /gsd:plan-phase."""
        br = self.bridge.invoke_skill("gsd:plan-phase", str(phase))
        return self.bridge_to_result(br)

    def execute_phase(self, phase: int) -> ToolResult:
        """Execute a specific phase via /gsd:execute-phase."""
        br = self.bridge.invoke_skill("gsd:execute-phase", str(phase))
        return self.bridge_to_result(br)

    def progress(self) -> ToolResult:
        """Check project progress via /gsd:progress."""
        br = self.bridge.invoke_skill("gsd:progress")
        return self.bridge_to_result(br)
