"""GSD adapter — thin wrapper around context.py for project setup.

The full GSD skill system (/gsd:plan-phase, /gsd:execute-phase, /gsd:progress)
runs natively inside Claude Code sessions. Use `flowstate launch gsd <phase>`
to get the exact commands.

This adapter handles initial project setup by delegating to context.py
for file generation, with optional LLM enrichment.
"""

from __future__ import annotations


from flowstate.context import write_context_files
from flowstate.state import FlowStateModel
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_ROADMAP = """\
# Roadmap

## Milestones
{milestones}

## Status
- Phase: Initialization
- State: Ready for planning

---
*Generated by FlowState (mock mode)*
"""


class GSDAdapter(ToolAdapter):
    name = "gsd"

    def new_project(self, state: FlowStateModel) -> ToolResult:
        """Generate project context files via context.py.

        This replaces the old approach of calling /gsd:new-project via subprocess.
        Context files are generated deterministically from interview answers.
        """
        if self.dry_run:
            answers = state.interview
            roadmap_path = self.root / ".planning" / "ROADMAP.md"
            roadmap_path.parent.mkdir(exist_ok=True)
            milestone_text = (
                "\n".join(f"{i}. {m}" for i, m in enumerate(answers.milestones, 1))
                or "1. Define milestones"
            )
            roadmap_path.write_text(MOCK_ROADMAP.format(milestones=milestone_text))
            return ToolResult(
                success=True,
                output="[dry-run] Context files written to .planning/",
                artifacts=[str(roadmap_path)],
            )

        created = write_context_files(state, self.root)
        artifacts = [str(p) for p in created]

        return ToolResult(
            success=True,
            output=f"Context files written: {len(created)} files to .planning/, .claude/, research/",
            artifacts=artifacts,
        )
