"""Gstack adapter — strategy via Garry Tan /office-hours + environment init.

Live mode uses the claude CLI to:
1. Initialize a Flox/Nix environment via the flox:flox-environments skill.
2. Run a strategic pressure-test (office hours) on the project idea.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_STRATEGY = """\
# Strategy: Office Hours Output

## Core Problem
{problem}

## 10x Vision
{vision}

## Pressure Test
- **Market fit**: Validated against the core problem statement.
- **Scalability**: Architecture supports 10x growth path.
- **Risk**: Key risks identified and mitigated in milestone planning.

---
*Generated by FlowState (mock mode)*
"""

OFFICE_HOURS_SYSTEM = dedent("""\
    You are a startup advisor running office hours in the style of Garry Tan.
    Your job is to pressure-test the idea and produce a strategic assessment.

    For each idea, evaluate:
    1. **Problem clarity**: Is the core problem real and urgent?
    2. **10x potential**: Does the vision represent a 10x improvement?
    3. **Feasibility**: Can this be built with the stated architecture?
    4. **Risks**: What are the top 3 risks and mitigations?
    5. **Recommendation**: Ship, pivot, or kill — with rationale.

    Output a structured Markdown document. Be direct and honest.
""").strip()


def _build_office_hours_prompt(answers: InterviewAnswers) -> str:
    milestones = "\n".join(f"- {m}" for m in answers.milestones) or "- TBD"
    return dedent(f"""\
        # Office Hours: Strategic Review

        ## Core Problem
        {answers.core_problem}

        ## 10x Vision
        {answers.ten_x_vision}

        ## Proposed Milestones
        {milestones}

        ## Architecture
        Pattern: {answers.architecture_pattern or 'not specified'}
        Test coverage target: {answers.test_coverage}%

        Evaluate this idea. Produce a structured strategy document.
    """)


class GstackAdapter(ToolAdapter):
    name = "gstack"

    def init_stack(self) -> ToolResult:
        """Initialize the reproducible dev environment via Flox."""
        if self.dry_run:
            return ToolResult(
                success=True,
                output="[dry-run] Would invoke flox:flox-environments skill",
            )

        br = self.bridge.invoke_skill("flox:flox-environments")
        return self.bridge_to_result(br)

    def office_hours(self, answers: InterviewAnswers) -> ToolResult:
        """Run the strategic pressure-test on the project idea."""
        strategy_path = self.root / "research" / "strategy.md"
        strategy_path.parent.mkdir(exist_ok=True)

        if self.dry_run:
            content = MOCK_STRATEGY.format(
                problem=answers.core_problem or "Not specified",
                vision=answers.ten_x_vision or "Not specified",
            )
            strategy_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Strategy report written to {strategy_path}",
                artifacts=[str(strategy_path)],
            )

        prompt = _build_office_hours_prompt(answers)
        br = self.bridge.run(
            prompt,
            system_prompt=OFFICE_HOURS_SYSTEM,
            allowed_tools=["WebSearch"],
            max_turns=5,
        )

        if br.success and br.output.strip():
            strategy_path.write_text(br.output)
            return ToolResult(
                success=True,
                output=f"Strategy report written to {strategy_path}",
                artifacts=[str(strategy_path)],
            )

        return self.bridge_to_result(br)
