"""Gstack adapter — strategy via Garry Tan /office-hours + environment init."""

from __future__ import annotations

from pathlib import Path

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_STRATEGY = """\
# Strategy: Office Hours Output

## Core Problem
{problem}

## 10x Vision
{vision}

## Pressure Test
- **Market fit**: Validated against the core problem statement.
- **Scalability**: Architecture supports 10x growth path.
- **Risk**: Key risks identified and mitigated in milestone planning.

---
*Generated by FlowState (mock mode)*
"""


class GstackAdapter(ToolAdapter):
    name = "gstack"

    def init_stack(self) -> ToolResult:
        if self.dry_run:
            return ToolResult(
                success=True,
                output="[dry-run] Would execute: gstack /init-stack (Nix/Flox environment)",
                artifacts=[],
            )
        return self.run_cmd(["gstack", "/init-stack"])

    def office_hours(self, answers: InterviewAnswers) -> ToolResult:
        strategy_path = self.root / "research" / "strategy.md"
        strategy_path.parent.mkdir(exist_ok=True)

        if self.dry_run:
            content = MOCK_STRATEGY.format(
                problem=answers.core_problem or "Not specified",
                vision=answers.ten_x_vision or "Not specified",
            )
            strategy_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Strategy report written to {strategy_path}",
                artifacts=[str(strategy_path)],
            )

        result = self.run_cmd([
            "gstack", "/office-hours",
            "--problem", answers.core_problem,
            "--vision", answers.ten_x_vision,
        ])
        if result.success and result.output:
            strategy_path.write_text(result.output)
            result.artifacts.append(str(strategy_path))
        return result
