"""Research adapter — split-topic research via claude --print.

Splits research_focus by comma into individual topics, runs one short
bridge call per topic (3 turns, 60s timeout), and merges results into
research/report.md.

Renamed from autoresearch.py — this is NOT Karpathy's autoresearch.
"""

from __future__ import annotations

from textwrap import dedent

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_REPORT = """\
# Research Report

## Focus Areas
{focus}

## Findings
- **Libraries**: Analysis pending research integration.
- **Edge Cases**: Identified areas requiring deeper investigation.
- **References**: Queued for search.

## Recommendations
1. Proceed with initial architecture while research continues.
2. Flag blocking unknowns for async resolution.

---
*Generated by FlowState (mock mode)*
"""

RESEARCH_SYSTEM_PROMPT = dedent("""\
    You are an expert technical researcher. Produce a concise Markdown research
    section — under 50 lines. Do at most 2 web searches. For the given topic:
    1. One targeted search for current best practice.
    2. Pros/cons of top 2 approaches (brief table).
    3. One concrete recommendation with rationale.
    Output ONLY the Markdown. No preamble, no summaries, no follow-up offers.
""").strip()


def _split_topics(research_focus: str) -> list[str]:
    """Split comma-separated research focus into individual topics."""
    topics = [t.strip() for t in research_focus.split(",") if t.strip()]
    return topics if topics else [research_focus or "general research"]


def _build_topic_prompt(topic: str, answers: InterviewAnswers) -> str:
    """Build a focused research prompt for a single topic."""
    parts = [f"# Research: {topic}"]
    if answers.core_problem:
        parts.append(f"\nContext: {answers.core_problem}")
    if answers.architecture_pattern:
        parts.append(f"Architecture constraint: {answers.architecture_pattern}")
    parts.append(
        f"\nResearch '{topic}' — current best practices, top approaches, "
        "and a concrete recommendation."
    )
    return "\n".join(parts)


class ResearchAdapter(ToolAdapter):
    name = "research"

    def execute(self, answers: InterviewAnswers) -> ToolResult:
        """Run research — one bridge call per topic, merge results."""
        report_dir = self.root / "research"
        report_dir.mkdir(exist_ok=True)
        report_path = report_dir / "report.md"

        topics = _split_topics(answers.research_focus)

        if self.dry_run:
            content = MOCK_REPORT.format(focus=", ".join(topics))
            report_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Research report written to {report_path}",
                artifacts=[str(report_path)],
            )

        # One call per topic — short and focused
        sections = []
        for topic in topics:
            prompt = _build_topic_prompt(topic, answers)
            prior = self.get_memory_context(topic)
            if prior:
                prompt = prior + "\n\n---\n\n" + prompt
            br = self.bridge.run(
                prompt,
                system_prompt=RESEARCH_SYSTEM_PROMPT,
                allowed_tools=["WebSearch", "WebFetch"],
                max_turns=3,
                model="sonnet",
            )
            if br.success and br.output.strip():
                sections.append(br.output.strip())
            else:
                sections.append(f"## {topic}\n\n*Research failed: {br.error or 'no output'}*\n")

        report = "# Research Report\n\n" + "\n\n---\n\n".join(sections) + "\n"
        report_path.write_text(report)

        return ToolResult(
            success=True,
            output=f"Research report written to {report_path} ({len(topics)} topics)",
            artifacts=[str(report_path)],
        )
