"""Strategy adapter — pressure-test via claude --print.

Single focused bridge call for strategic assessment. Produces
research/strategy.md with a structured evaluation.

Renamed from gstack.py — this is NOT using Gstack slash commands.
"""

from __future__ import annotations

import re
from textwrap import dedent

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

# Gstack's core mechanism (MECH-02): a scored review, not a free-form call.
# The five dimensions mirror the numbered evaluation axes in STRATEGY_SYSTEM_PROMPT.
_RUBRIC_DIMENSIONS = ("problem_clarity", "ten_x_potential", "feasibility", "risk", "recommendation")
_VERDICTS = ("ship", "pivot", "kill")

MOCK_STRATEGY = """\
# Strategy: Pressure Test

## Core Problem
{problem}

## 10x Vision
{vision}

## Assessment
- **Market fit**: Validated against the core problem statement.
- **Scalability**: Architecture supports 10x growth path.
- **Risk**: Key risks identified and mitigated in milestone planning.

---
*Generated by FlowState (mock mode)*
"""

STRATEGY_SYSTEM_PROMPT = dedent("""\
    You are a startup advisor running a strategic pressure-test.
    Your job is to evaluate the idea honestly and produce a strategic assessment.

    For each idea, evaluate:
    1. **Problem clarity**: Is the core problem real and urgent?
    2. **10x potential**: Does the vision represent a 10x improvement?
    3. **Feasibility**: Can this be built with the stated architecture?
    4. **Risks**: What are the top 3 risks and mitigations?
    5. **Recommendation**: Ship, pivot, or kill — with rationale.

    Output a structured Markdown document. Be direct and honest.

    After the prose, you MUST APPEND a machine-readable rubric as a fenced code
    block. Emit exactly one `dimension: <0-10>` line per dimension key below
    (integer scores only), then a `verdict:` line with one of ship/pivot/kill:

    ```rubric
    problem_clarity: <0-10>
    ten_x_potential: <0-10>
    feasibility: <0-10>
    risk: <0-10>
    recommendation: <0-10>
    verdict: <ship|pivot|kill>
    ```
""").strip()


def _parse_rubric(output: str) -> tuple[dict[str, int], str] | None:
    """Parse the model's scored rubric from raw bridge output.

    Extracts a `dimension: N` pair for each key in ``_RUBRIC_DIMENSIONS`` (N an
    integer clamped-validated to 0-10) plus a `verdict:` line validated against
    ``_VERDICTS`` (case-insensitive, normalized to lowercase). The search is
    tolerant — it scans the whole output rather than requiring the fenced block —
    but strictly regex-only: no dynamic evaluation of untrusted model text.

    Returns ``(scores, verdict)`` only when ALL five dimensions AND a valid
    verdict are present and in-range; otherwise returns ``None`` so the caller
    can surface an HON-04 failure instead of writing a weak artifact.
    """
    scores: dict[str, int] = {}
    for dim in _RUBRIC_DIMENSIONS:
        match = re.search(rf"\b{re.escape(dim)}\s*:\s*(\d+)\b", output, re.IGNORECASE)
        if match is None:
            return None
        value = int(match.group(1))
        if not 0 <= value <= 10:
            return None
        scores[dim] = value

    verdict_match = re.search(r"\bverdict\s*:\s*(ship|pivot|kill)\b", output, re.IGNORECASE)
    if verdict_match is None:
        return None
    verdict = verdict_match.group(1).lower()

    return scores, verdict


def _build_pressure_test_prompt(answers: InterviewAnswers) -> str:
    milestones = "\n".join(f"- {m}" for m in answers.milestones) or "- TBD"
    return dedent(f"""\
        # Strategic Pressure Test

        ## Core Problem
        {answers.core_problem}

        ## 10x Vision
        {answers.ten_x_vision}

        ## Proposed Milestones
        {milestones}

        ## Architecture
        Pattern: {answers.architecture_pattern or "not specified"}
        Test coverage target: {answers.test_coverage}%

        Evaluate this idea. Produce a structured strategy document.
    """)


class StrategyAdapter(ToolAdapter):
    name = "strategy"

    def pressure_test(self, answers: InterviewAnswers) -> ToolResult:
        """Run the strategic pressure-test on the project idea."""
        strategy_path = self.root / "research" / "strategy.md"
        strategy_path.parent.mkdir(exist_ok=True)

        if self.dry_run:
            content = MOCK_STRATEGY.format(
                problem=answers.core_problem or "Not specified",
                vision=answers.ten_x_vision or "Not specified",
            )
            strategy_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Strategy report written to {strategy_path}",
                artifacts=[str(strategy_path)],
            )

        prompt = _build_pressure_test_prompt(answers)
        # prior_knowledge is built ONCE upstream in orchestrator.run_pipeline and
        # injected via __init__. Same block as Research/GSD adapters so the
        # server-side prompt cache hits across pipeline steps.
        prior = self.prior_knowledge or ""
        if prior:
            prompt = prior + "\n\n---\n\n" + prompt
        br = self.bridge.run(
            prompt,
            system_prompt=STRATEGY_SYSTEM_PROMPT,
            allowed_tools=["WebSearch"],
            max_turns=5,
            model="sonnet",
            output_format="json",
        )

        if br.success and br.output.strip():
            parsed = _parse_rubric(br.output)
            if parsed is None:
                # MECH-02: an unparseable/missing rubric is a FAILURE, not a
                # silently-written weak artifact — surfaced via the HON-04 path.
                return ToolResult(
                    success=False,
                    output=br.output,
                    error="unparseable rubric: missing per-dimension 0-10 scores "
                    "or ship/pivot/kill verdict",
                    artifacts=[],
                )
            scores, verdict = parsed
            score_lines = "\n".join(f"- {dim}: {scores[dim]}" for dim in _RUBRIC_DIMENSIONS)
            rubric_section = f"\n\n## Rubric\n\n{score_lines}\n- **Verdict:** {verdict}\n"
            strategy_path.write_text(br.output + rubric_section)
            score_summary = " ".join(f"{dim}={scores[dim]}" for dim in _RUBRIC_DIMENSIONS)
            return ToolResult(
                success=True,
                output=f"Strategy verdict: {verdict} ({score_summary})",
                artifacts=[str(strategy_path)],
            )

        return ToolResult(
            success=False,
            output=br.output,
            error=br.error or "strategy produced empty output",
            artifacts=[],
        )
