"""Strategy adapter — pressure-test via claude --print.

Single focused bridge call for strategic assessment. Produces
research/strategy.md with a structured evaluation.

Renamed from gstack.py — this is NOT using Gstack slash commands.
"""

from __future__ import annotations

from textwrap import dedent

from flowstate.state import InterviewAnswers
from flowstate.tools.base import ToolAdapter, ToolResult

MOCK_STRATEGY = """\
# Strategy: Pressure Test

## Core Problem
{problem}

## 10x Vision
{vision}

## Assessment
- **Market fit**: Validated against the core problem statement.
- **Scalability**: Architecture supports 10x growth path.
- **Risk**: Key risks identified and mitigated in milestone planning.

---
*Generated by FlowState (mock mode)*
"""

STRATEGY_SYSTEM_PROMPT = dedent("""\
    You are a startup advisor running a strategic pressure-test.
    Your job is to evaluate the idea honestly and produce a strategic assessment.

    For each idea, evaluate:
    1. **Problem clarity**: Is the core problem real and urgent?
    2. **10x potential**: Does the vision represent a 10x improvement?
    3. **Feasibility**: Can this be built with the stated architecture?
    4. **Risks**: What are the top 3 risks and mitigations?
    5. **Recommendation**: Ship, pivot, or kill — with rationale.

    Output a structured Markdown document. Be direct and honest.
""").strip()


def _build_pressure_test_prompt(answers: InterviewAnswers) -> str:
    milestones = "\n".join(f"- {m}" for m in answers.milestones) or "- TBD"
    return dedent(f"""\
        # Strategic Pressure Test

        ## Core Problem
        {answers.core_problem}

        ## 10x Vision
        {answers.ten_x_vision}

        ## Proposed Milestones
        {milestones}

        ## Architecture
        Pattern: {answers.architecture_pattern or "not specified"}
        Test coverage target: {answers.test_coverage}%

        Evaluate this idea. Produce a structured strategy document.
    """)


class StrategyAdapter(ToolAdapter):
    name = "strategy"

    def pressure_test(self, answers: InterviewAnswers) -> ToolResult:
        """Run the strategic pressure-test on the project idea."""
        strategy_path = self.root / "research" / "strategy.md"
        strategy_path.parent.mkdir(exist_ok=True)

        if self.dry_run:
            content = MOCK_STRATEGY.format(
                problem=answers.core_problem or "Not specified",
                vision=answers.ten_x_vision or "Not specified",
            )
            strategy_path.write_text(content)
            return ToolResult(
                success=True,
                output=f"[dry-run] Strategy report written to {strategy_path}",
                artifacts=[str(strategy_path)],
            )

        prompt = _build_pressure_test_prompt(answers)
        br = self.bridge.run(
            prompt,
            system_prompt=STRATEGY_SYSTEM_PROMPT,
            allowed_tools=["WebSearch"],
            max_turns=5,
        )

        if br.success and br.output.strip():
            strategy_path.write_text(br.output)
            return ToolResult(
                success=True,
                output=f"Strategy report written to {strategy_path}",
                artifacts=[str(strategy_path)],
            )

        return self.bridge_to_result(br)
